"""Add

Revision ID: c178f2f678d8
Revises: 35a1ba9b0db6
Create Date: 2025-04-08 14:37:48.651284

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c178f2f678d8"
down_revision: Union[str, None] = "35a1ba9b0db6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "genre",
        existing_type=postgresql.ENUM("Fiction", "Non-Fiction", "Science", "History", name="genre"),
        type_=sa.Enum("FICTION", "NON_FICTION", "SCIENCE", "HISTORY", name="genre", native_enum=False),
        existing_nullable=False,
        existing_server_default=sa.text("'Fiction'::genre"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "genre",
        existing_type=sa.Enum("FICTION", "NON_FICTION", "SCIENCE", "HISTORY", name="genre", native_enum=False),
        type_=postgresql.ENUM("Fiction", "Non-Fiction", "Science", "History", name="genre"),
        existing_nullable=False,
        existing_server_default=sa.text("'Fiction'::genre"),
    )
    # ### end Alembic commands ###
